


##
# Your previous /Users/xuqiang/.bash_profile file was backed up as /Users/xuqiang/.bash_profile.macports-saved_2017-10-09_at_13:54:55
##

# MacPorts Installer addition on 2017-10-09_at_13:54:55: adding an appropriate PATH variable for use with MacPorts.
#export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

#export PATH=/usr/local/mysql/bin:$PATH

#added by Xuqiang Fang for Apache Flink
#export PATH=/usr/local/Cellar/apache-flink/1.3.2/libexec/bin:$PATH
export LDFLAGS="-L/usr/local/opt/openblas/lib"
export CPPFLAGS="-I/usr/local/opt/openblas/include"
export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home"
export HADOOP_CLASSPATH="$JAVA_HOME/lib/tools.jar"

export FLINK_HOME="/usr/local/Cellar/apache-flink/1.6.1/libexec/"
export SPARK_HOME="/usr/local/Cellar/apache-spark/2.3.1/libexec/"
export HADOOP_HOME="/usr/local/Cellar/hadoop/2.8.2/"

#added by Xuqiang Fang for Hadoop
alias hstart="/usr/local/Cellar/hadoop/2.8.2/sbin/start-dfs.sh;/usr/local/Cellar/hadoop/2.8.2/sbin/start-yarn.sh"
alias hstop="/usr/local/Cellar/hadoop/2.8.2/sbin/stop-yarn.sh;/usr/local/Cellar/hadoop/2.8.2/sbin/stop-dfs.sh"
alias cl='clear'
##more alias
alias ll="ls -laF"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion




#export PATH="/usr/local/opt/bison/bin:$PATH"



#added by Xuqiang Fang for language setting for R
export LC_ALL=en_US
### added by xuqiang fang for issues opening slime in emacs
export LANG=en_US
#added by Xuqiang Fang for llvm
#export PATH="/usr/local/opt/llvm/bin:$PATH"


#added by xuqiang fang for TERM
export TERM='xterm-256color'

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/mysql/bin:/usr/local/opt/llvm/bin:/usr/local/opt/bison/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/python/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/texlive/2016/bin/x86_64-darwin:$FLINK_HOME/lib/"

export ANDROID_HOME="$HOME/Library/Android/Sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
##added by xuqiang fang for default python interpreter in virtualenv
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/xuqiang/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/xuqiang/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/xuqiang/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/xuqiang/Downloads/google-cloud-sdk/completion.bash.inc'; fi
